// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7vviDSz626_WaLAvbQbQjLf9DI8KmBsI',
    appId: '1:791888086894:web:e48d8504319e573f62a37f',
    messagingSenderId: '791888086894',
    projectId: 'fir-project-3a3c3',
    authDomain: 'fir-project-3a3c3.firebaseapp.com',
    storageBucket: 'fir-project-3a3c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz42Cx_kNKKbBD8F0yeEajkhwEToDQUuU',
    appId: '1:791888086894:android:c0d3234bb79ead7162a37f',
    messagingSenderId: '791888086894',
    projectId: 'fir-project-3a3c3',
    storageBucket: 'fir-project-3a3c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlOSb2MnYPVvgaYqrmq7LCcQiT0qzLbTs',
    appId: '1:791888086894:ios:e6b4c8c0379451cf62a37f',
    messagingSenderId: '791888086894',
    projectId: 'fir-project-3a3c3',
    storageBucket: 'fir-project-3a3c3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlOSb2MnYPVvgaYqrmq7LCcQiT0qzLbTs',
    appId: '1:791888086894:ios:e6b4c8c0379451cf62a37f',
    messagingSenderId: '791888086894',
    projectId: 'fir-project-3a3c3',
    storageBucket: 'fir-project-3a3c3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7vviDSz626_WaLAvbQbQjLf9DI8KmBsI',
    appId: '1:791888086894:web:a54a10d23dd291c562a37f',
    messagingSenderId: '791888086894',
    projectId: 'fir-project-3a3c3',
    authDomain: 'fir-project-3a3c3.firebaseapp.com',
    storageBucket: 'fir-project-3a3c3.firebasestorage.app',
  );
}
