// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvKrZQP9I59dmVnGOymg2_PU5h0WTZg3A',
    appId: '1:883394480316:web:b90a1cd70dd2d43314e8b9',
    messagingSenderId: '883394480316',
    projectId: 'to-do-f4759',
    authDomain: 'to-do-f4759.firebaseapp.com',
    storageBucket: 'to-do-f4759.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfbyjEAM_voCioX6rw7Q-GaLZDzalkRC8',
    appId: '1:883394480316:android:14ba8e630db4e81b14e8b9',
    messagingSenderId: '883394480316',
    projectId: 'to-do-f4759',
    storageBucket: 'to-do-f4759.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGM9haidVPjUc4ou0PjsoEnIDeWg5HXE4',
    appId: '1:883394480316:ios:ebccca0de004710d14e8b9',
    messagingSenderId: '883394480316',
    projectId: 'to-do-f4759',
    storageBucket: 'to-do-f4759.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGM9haidVPjUc4ou0PjsoEnIDeWg5HXE4',
    appId: '1:883394480316:ios:ebccca0de004710d14e8b9',
    messagingSenderId: '883394480316',
    projectId: 'to-do-f4759',
    storageBucket: 'to-do-f4759.firebasestorage.app',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvKrZQP9I59dmVnGOymg2_PU5h0WTZg3A',
    appId: '1:883394480316:web:e2636d21b6f12d2b14e8b9',
    messagingSenderId: '883394480316',
    projectId: 'to-do-f4759',
    authDomain: 'to-do-f4759.firebaseapp.com',
    storageBucket: 'to-do-f4759.firebasestorage.app',
  );
}
